version: '3.8'

services:
  bvg-bot:
    build: .
    container_name: bvg-sbahn-discord-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Europe/Berlin
