services:
  - type: web
    name: bvg-sbahn-discord-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    region: frankfurt
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DISCORD_WEBHOOK_URL
        sync: false
      - key: CHECK_INTERVAL
        value: "300"
      - key: LOG_LEVEL
        value: "INFO"
      - key: PORT
        value: "10000"
      - key: PYTHON_VERSION
        value: 3.11.6
