name: VBB Discord Bot

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install Dependencies
        run: npm install
      
      - name: Create state directory
        run: mkdir -p state
      
      - name: Run Bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          VBB_API_KEY: ${{ secrets.VBB_API_KEY }}
          UPDATE_INTERVAL_MINUTES: ${{ secrets.UPDATE_INTERVAL_MINUTES }}
          FILTER_LINES: ${{ secrets.FILTER_LINES }}
          MIN_DELAY: ${{ secrets.MIN_DELAY }}
          GITHUB_ACTIONS: 'true'
        run: npm start
      
      - name: Commit State
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add state/
          git diff --quiet && git diff --staged --quiet || git commit -m "Update bot state [skip ci]"
          git push
        continue-on-error: true
